version: '3.8'

services:
  wiremock-setup-core:
    image: rodolpheche/wiremock
    container_name: wiremock-setup-example
    ports:
      - "8031:8080"
    volumes:
      - ./wiremock/stubs/__files/:/home/wiremock/__files/
      - ./wiremock/stubs/mappings/:/home/wiremock/mappings/
    command:
      - -verbose
      - -global-response-templating
  postgres:
    image: postgres:11.13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000