spring:
  application:
    name: test-example
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
    ddl-auto: create-drop
    show-sql: true
server:
  port: 8282